### ISSUE TITLE
Mixed-Up Recipes

### ISSUE THREAD

**Issue by Nimflora** [ArtixAllMighty/ExSartagine#3]
Recipes such as the [meat roll,](https://gyazo.com/5c96f62c57815215c5a7dc09de802db4) [vegetable bread,](https://gyazo.com/5c597898edfc3ed5ade5c6558ea6b79f) [fish pizza,](https://gyazo.com/c93300c186927716985272f928c4606a) [meat pizza,](https://gyazo.com/d21b838cae9c34b762eccbdd753fb2b7) and [plain](https://gyazo.com/413447e827e5b7960973111a87555495) [pizza](https://gyazo.com/0f9bd16192a80b63fcbf5e951abf31cf) are wrong or mixed, while recipes such as Raw Vegetable Bread and Raw Meat Roll have no recipes at all.

**Comment by MinecraftWero** [comment]
thanks for letting us know, it will be fixed in the next update!

**Comment by AbsolemJackdaw** [comment]
I'm pretty sure they are all allright. 
May I ask you @Nimflora to double check your .jar and tell me which recipe .json files are off ?

**Comment by Nimflora** [comment]
I'm sorry, I'm on a mac, I don't know how to open it ;^;

**Comment by TeetoKaziim** [comment]
https://github.com/ArtixAllMighty/ExSartagine/blob/master/src/main/resources/assets/exsartagine/recipes/bread/breadVeggie.json
Has:
```
"result": {
        "item": "exsartagine:breadVeggie"
    }
```
Which probably should be ``breadVeggieRaw`` or whatever would output this item:
![image](https://user-images.githubusercontent.com/25490944/50569709-ddf6ac00-0d31-11e9-8b6f-a76f25c40376.png)

Then, there's:
https://github.com/ArtixAllMighty/ExSartagine/blob/master/src/main/resources/assets/exsartagine/recipes/bread/breadMeat.json
Which currently has:
``"item": "exsartagine:breadMeat",``
as a result, while the ``breadmeatraw`` is also uncraftable, and further, has the exact same inputs as the Veggie bread recipe above, which leads to a recipe conflict, but also, it seems like it should be calling for some kind of meat instead of ``cropVegetable``.
